
services:
  - type: web
    name: papi-2-ai
    env: python
    # This command installs the tools listed in requirements.txt
    buildCommand: pip install -r requirements.txt
    # This command starts the server using Gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
